#!/bin/sh
#
# This is the configuration file for the live ISO user (vyatta/vyatta, refused by install image)
#

LIVE_USERNAME=vyatta
LIVE_USER_FULLNAME="NuDanOS live user"
LIVE_USER_DEFAULT_GROUPS="${LIVE_USER_DEFAULT_GROUPS},vyattacfg"
export LIVE_USERNAME LIVE_USER_FULLNAME LIVE_USER_DEFAULT_GROUPS
