from __future__ import annotations

import importlib.util
import os
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("gen", os.path.join(HERE, "gen-manifest.py"))
gen = importlib.util.module_from_spec(spec)
spec.loader.exec_module(gen)

DATA = {
    "inventory": {"configd": {"kind": "original"}, "strongswan": {"kind": "fork"},
                  "vyatta-poe": {"kind": "original"}, "yang": {"kind": "original"},
                  "vyatta-controller": {"kind": "original"}, "tests": {"kind": "original"},
                  "vyatta-service-dhcp": {"kind": "original"}, "aaa": {"kind": "original"}},
    "m1": {"configd", "vyatta-service-dhcp"},
    "edges": {"configd": ["yang"], "yang": ["dh-yang"], "dh-yang": []},
}


class ClassifyTest(unittest.TestCase):
    def test_runtime_closure_is_milestone_1(self):
        e = gen.classify("configd", DATA)
        self.assertEqual((e["kind"], e["milestone"], e["ref"]), ("danos", "1.0", "trixie"))
        self.assertEqual(e["repo"], "https://github.com/nudanos/configd")

    def test_build_dependency_closure_is_milestone_1(self):
        self.assertEqual(gen.classify("yang", DATA)["milestone"], "1.0")

    def test_rewrite_packages_are_1_1(self):
        self.assertEqual(gen.classify("vyatta-service-dhcp", DATA)["milestone"], "1.1")

    def test_fork_table_wins(self):
        e = gen.classify("strongswan", DATA)
        self.assertEqual((e["kind"], e["track"]), ("upstream", "latest"))
        self.assertEqual(e["packaging"], "https://salsa.debian.org/debian/strongswan.git")

    def test_hardware_dropped_dataplane_m2_reference_and_rest_later(self):
        self.assertEqual(gen.classify("vyatta-poe", DATA)["kind"], "drop")
        self.assertEqual(gen.classify("vyatta-controller", DATA)["milestone"], "2")
        self.assertEqual(gen.classify("tests", DATA)["kind"], "reference")
        self.assertEqual(gen.classify("aaa", DATA)["milestone"], "later")

    def test_netconf_forks_are_replaced(self):
        self.assertEqual(gen.classify("libnetconf", DATA)["kind"], "drop")
        self.assertEqual(gen.classify("pyang", DATA)["kind"], "drop")

    def test_frr_is_left_to_the_apt_entry(self):
        self.assertIsNone(gen.classify("frr", DATA))

    def test_pilot_is_ready(self):
        self.assertTrue(gen.classify("configd", DATA).get("ready") is None)
        d = dict(DATA, inventory=dict(DATA["inventory"], **{"dh-yang": {"kind": "original"}}))
        self.assertTrue(gen.classify("dh-yang", d)["ready"])


class EmitTest(unittest.TestCase):
    def test_quotes_values_that_yaml_would_misread(self):
        out = gen.emit([{"name": "x", "kind": "apt", "milestone": "1.0",
                         "packages": {"frr": "10.7.1-0~deb13u1"}, "note": "a: b # c"}])
        self.assertIn('milestone: "1.0"', out)
        self.assertIn('frr: "10.7.1-0~deb13u1"', out)
        self.assertIn('note: "a: b # c"', out)
        self.assertTrue(out.startswith("# Generated by tools/gen-manifest.py"))


if __name__ == "__main__":
    unittest.main()
